SELECT FIRST_NAME FROM ACTOR
WHERE FIRST_NAME = "SCARLETT";
SELECT LAST_NAME FROM ACTOR 
WHERE LAST_NAME = "JOHANSSON";
SELECT * FROM FILM;
SELECT * FROM RENTAL;
SELECT * FROM INVENTORY;
SELECT COUNT(FILM_ID) FROM FILM;
SELECT COUNT(RENTAL_ID) FROM RENTAL;
SELECT MIN(RENTAL_DURATION) AS MIN_DURATION FROM FILM;
SELECT MAX(RENTAL_DURATION) AS MAX_DURATION FROM FILM;
SELECT AVG(LENGTH) AS AVERAGE_LENGTH FROM FILM;
SELECT (1+((((AVG(LENGTH)/60)-1)*60)/100)) AS AVERAGE_HOUR_LENGTH FROM FILM;
SELECT COUNT(FILM_ID) FROM FILM WHERE LENGTH > 180;
SELECT LOWER(EMAIL) FROM CUSTOMER;
SELECT TITLE FROM FILM;
SELECT MAX(LENGTH(TITLE)) FROM FILM;
SELECT *
FROM FILM 
WHERE LENGTH(TITLE) = (SELECT MAX(LENGTH(TITLE)) FROM FILM);